 


#ifndef TIMERS__PRIVATE_H_
#define TIMERS__PRIVATE_H_
/* MODES*/
#define TMR0_CTC_MODE 1
#define TMR0_NORMAL_MODE 2
#define TMR0_FAST_PWM_MODE 3 
#define TMR0_PHASE_CORRECT_MODE 4
/* PRESCALER*/
#define TMR0_PRESCALER_1 0
#define TMR0_PRESCALER_8 1
#define TMR0_PRESCALER_64 2
#define TMR0_PRESCALER_256 3
#define TMR0_PRESCALER_1024 4

/*FAST PWM */
#define TMR0_PWM_NONINVERTING 1
#define TMR0_PWM_INVERTING 2






#endif /* TIMERS__PRIVATE_H_ */