 


#ifndef TMR1_CONFIG_H_
#define TMR1_CONFIG_H_
/* Select Mode
1-TMR0_NORMAL_MODE_0
2-TMR0_CTC_MODE_4
3-TMR0_FAST_PWM_MODE_14

*/
#define TMR1_MODE TMR1_FAST_PWM_MODE_14
#define TMR1_PWM_MOD TMR1_PWM_NONINVERTING
#define TMR1_PRESCALER TMR1_PRESCALER_64



#endif /* TMR1_CONFIG_H_ */